#!/usr/bin/env bash
# This script is used to transfer files from client to remote server

path_to_file=$1
ip=$2
username=$3
path_to_ssh_key=$4

if [ -z "$path_to_file" ] || [ -z "$ip" ] || [ -z "$username" ] || [ -z "$path_to_ssh_key" ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 1
fi

scp -o StrictHostKeyChecking=no -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:"~
