#!/usr/bin/env bash
# script to install Nginx

apt-get -y update
apt-get -y install nginx
ufw allow 'Nginx HTTP'
mkdir -p /var/www/html
echo 'Hello World!' > /var/www/html/index.html

echo "http {
	server {
		listen 80;
		
		root /var/www/html;
		
		location / {
			index.html;
		}
	}
}

events { }
" > /etc/nginx/nginx.conf
service nginx start
