#!/usr/bin/env bash
# Configures a new ubuntu machine by installing
# Nginx where it should be listening on port 80
# Serve a page that would return a Hello World string
# This scripts also configures the default webpage served to be "Hello World"

sudo apt-get update -y

sudo apt-get install nginx -y

echo "Hello World!" | sudo tee /var/www/html/index.html > /dev/null



sudo cp /etc/nginx/sites-available/default /etc/nginx/sites-available/default.bakup

sudo sed -i "53i $NEW_RULE" /etc/nginx/sites-available/default

sudo service nginx restart
