#!/usr/bin/env bash
# Configures Nginx server with custom response header

# Updating packages
sudo apt -y update
sudo apt -y install nginx
ufw allow 'Nginx HTTP'

# Creating an index page 
echo "Hello World!" | sudo tee /var/www/html/index.html

header="server_name _;\nadd_header X-Served-By \"$(hostname)\";"
sudo sed -i "s/server_name _;/$header/" /etc/nginx/sites-enabled/default

service nginx restart
